version: "3"
services:
  elasticsearch:
    image: elasticsearch:1.7.4
    ports:
      - "9200:9200"
      #- "9300"
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data/elasticsearch

  couchdb:
    image: couchdb
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
    volumes:
      - ./couchdb:/opt/couchdb/data
